/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_alberto.martinez;

import java.util.ArrayList;
import javax.swing.JOptionPane;

/**
 *
 * @author Alberto
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tf_nombreequipo = new javax.swing.JTextField();
        tf_presupuesto = new javax.swing.JTextField();
        js_copas = new javax.swing.JSpinner();
        tf_estadio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf_nombrejugador = new javax.swing.JTextField();
        tf_precio = new javax.swing.JTextField();
        tf_posicion = new javax.swing.JTextField();
        js_tecnica = new javax.swing.JSpinner();
        js_resistencia = new javax.swing.JSpinner();
        js_habilidad = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(tf_nombreequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 97, -1));
        jPanel1.add(tf_presupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 97, -1));

        js_copas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel1.add(js_copas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 100, -1));
        jPanel1.add(tf_estadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 97, -1));

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel2.setText("Presupuesto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel3.setText("# Copas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 60, -1));

        jLabel4.setText("Estadio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 60, -1));

        jLabel5.setText("Crear Equipo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jButton1.setText("CREAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, 60));

        jLabel6.setText("Crear Jugador");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));
        jPanel1.add(tf_nombrejugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 180, 80, -1));
        jPanel1.add(tf_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 210, 80, -1));
        jPanel1.add(tf_posicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 240, 80, -1));

        js_tecnica.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel1.add(js_tecnica, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 300, 40, 30));

        js_resistencia.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel1.add(js_resistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 40, -1));

        js_habilidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel1.add(js_habilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 40, -1));

        jButton2.setText("CREAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, 60));

        jLabel7.setText("Nombre");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jLabel8.setText("Precio");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        jLabel9.setText("Habilidad");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        jLabel10.setText("Tecnica");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        jLabel11.setText("Resitencia");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, -1));

        jLabel12.setText("Posicion");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jTabbedPane1.addTab("Crear", jPanel1);

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Listar", jPanel2);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Comprar", jPanel3);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 685, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 511, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Arbol", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            jugadores.add(new Jugador(tf_nombrejugador.getText(), Double.parseDouble(tf_precio.getText()), tf_posicion.getText(),true,  (Integer)js_habilidad.getValue(), (Integer)js_tecnica.getValue(), (Integer)js_resistencia.getValue()));
            JOptionPane.showMessageDialog(this, "Jugador creado con exito!");
            System.out.println(jugadores);
            
            tf_nombrejugador.setText("");
            tf_precio.setText("");
            tf_posicion.setText("");
            js_habilidad.setValue(0);
            js_tecnica.setValue(0);
            js_resistencia.setValue(0);
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error Vuelva a intentar");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            equipos.add(new Equipo(tf_nombreequipo.getText(), Double.parseDouble(tf_presupuesto.getText()), (Integer)js_copas.getValue(), tf_estadio.getText()));
            JOptionPane.showMessageDialog(this, "Equipo creado con exito!");
            
            tf_nombreequipo.setText("");
            tf_presupuesto.setText("");
            js_copas.setValue(0);
            tf_estadio.setText("");
            
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error Vuelva a intentar");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JSpinner js_copas;
    private javax.swing.JSpinner js_habilidad;
    private javax.swing.JSpinner js_resistencia;
    private javax.swing.JSpinner js_tecnica;
    private javax.swing.JTextField tf_estadio;
    private javax.swing.JTextField tf_nombreequipo;
    private javax.swing.JTextField tf_nombrejugador;
    private javax.swing.JTextField tf_posicion;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_presupuesto;
    // End of variables declaration//GEN-END:variables
ArrayList<Jugador>jugadores=new ArrayList();
ArrayList<Equipo>equipos=new ArrayList();
ArrayList<Equipo>Liga=new ArrayList();
ArrayList<Jugador>comprado=new ArrayList();
}
