/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package lab5_alberto.martinez;

import java.util.ArrayList;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;
import javax.swing.tree.DefaultMutableTreeNode;
import javax.swing.tree.DefaultTreeModel;

/**
 *
 * @author Alberto
 */
public class principal extends javax.swing.JFrame {

    /**
     * Creates new form principal
     */
    public principal() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        tf_nombreequipo = new javax.swing.JTextField();
        tf_presupuesto = new javax.swing.JTextField();
        js_copas = new javax.swing.JSpinner();
        tf_estadio = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        tf_nombrejugador = new javax.swing.JTextField();
        tf_precio = new javax.swing.JTextField();
        tf_posicion = new javax.swing.JTextField();
        js_tecnica = new javax.swing.JSpinner();
        js_resistencia = new javax.swing.JSpinner();
        js_habilidad = new javax.swing.JSpinner();
        jButton2 = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jl_equipos = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        jl_jugadores = new javax.swing.JList<>();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jButton7 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane3 = new javax.swing.JScrollPane();
        jt_liga = new javax.swing.JTree();
        jButton10 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());
        jPanel1.add(tf_nombreequipo, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, 97, -1));
        jPanel1.add(tf_presupuesto, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 97, -1));

        js_copas.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));
        jPanel1.add(js_copas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 100, -1));
        jPanel1.add(tf_estadio, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 97, -1));

        jLabel1.setText("Nombre");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 190, -1, -1));

        jLabel2.setText("Presupuesto");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        jLabel3.setText("# Copas");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, 60, -1));

        jLabel4.setText("Estadio");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, 60, -1));

        jLabel5.setText("Crear Equipo");
        jPanel1.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 150, -1, -1));

        jButton1.setText("CREAR");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 340, -1, 60));

        jLabel6.setText("Crear Jugador");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 150, -1, -1));
        jPanel1.add(tf_nombrejugador, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 180, 80, -1));
        jPanel1.add(tf_precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 210, 80, -1));
        jPanel1.add(tf_posicion, new org.netbeans.lib.awtextra.AbsoluteConstraints(489, 240, 80, -1));

        js_tecnica.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel1.add(js_tecnica, new org.netbeans.lib.awtextra.AbsoluteConstraints(517, 300, 40, 30));

        js_resistencia.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel1.add(js_resistencia, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 40, -1));

        js_habilidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, 100, 1));
        jPanel1.add(js_habilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 300, 40, -1));

        jButton2.setText("CREAR");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, -1, 60));

        jLabel7.setText("Nombre");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 180, -1, -1));

        jLabel8.setText("Precio");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 210, -1, -1));

        jLabel9.setText("Habilidad");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(350, 300, -1, -1));

        jLabel10.setText("Tecnica");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 300, -1, -1));

        jLabel11.setText("Resitencia");
        jPanel1.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 300, -1, -1));

        jLabel12.setText("Posicion");
        jPanel1.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 240, -1, -1));

        jTabbedPane1.addTab("Crear", jPanel1);

        jl_equipos.setModel(new DefaultListModel());
        jScrollPane1.setViewportView(jl_equipos);

        jl_jugadores.setModel(new DefaultListModel());
        jScrollPane2.setViewportView(jl_jugadores);

        jLabel13.setText("Equipos");

        jLabel14.setText("Jugadores");

        jButton3.setText("Actualizar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jButton4.setText("Eliminar");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jButton5.setText("Modificar");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });

        jButton6.setText("Eliminar");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });

        jButton7.setText("Modificar");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jLabel15.setText("Seleccione un equipo, despues seleccione el jugador que desea comprar para ese equipo");

        jButton8.setText("COMPRAR");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jButton9.setText("jButton9");
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(70, 70, 70)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 150, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(85, 85, 85))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                .addGap(289, 289, 289)
                                .addComponent(jButton3)
                                .addGap(98, 98, 98)
                                .addComponent(jButton9))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(48, 48, 48)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(29, 29, 29)
                                .addComponent(jButton8)
                                .addGap(31, 31, 31)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGroup(jPanel2Layout.createSequentialGroup()
                            .addGap(120, 120, 120)
                            .addComponent(jLabel13)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jLabel14)
                            .addGap(35, 35, 35)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(75, 75, 75)
                        .addComponent(jLabel15)))
                .addContainerGap(96, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton3)
                    .addComponent(jButton9))
                .addGap(39, 39, 39)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(jLabel13))
                .addGap(18, 18, 18)
                .addComponent(jLabel15)
                .addGap(8, 8, 8)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 46, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton6)
                    .addComponent(jButton5))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton4)
                    .addComponent(jButton7))
                .addGap(18, 18, 18))
        );

        jTabbedPane1.addTab("Listar", jPanel2);

        javax.swing.tree.DefaultMutableTreeNode treeNode1 = new javax.swing.tree.DefaultMutableTreeNode("Liga Española");
        jt_liga.setModel(new javax.swing.tree.DefaultTreeModel(treeNode1));
        jScrollPane3.setViewportView(jt_liga);

        jButton10.setText("jButton10");
        jButton10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton10ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(91, 91, 91)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 479, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(104, 104, 104)
                        .addComponent(jButton10)))
                .addContainerGap(115, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jButton10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 369, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(94, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Arbol", jPanel4);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        if (!equipos.isEmpty()) {
            System.out.println(equipos.get(0).jugadores);
            System.out.println(equipos.get(0).getPresupuesto());
        }
    }//GEN-LAST:event_jButton9ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        if (jl_jugadores.getSelectedIndex()>=0&&jl_equipos.getSelectedIndex()>=0) {
            int response=JOptionPane.showConfirmDialog(this, "Seguro que desea comprar?","Confirmar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

            if(response==JOptionPane.OK_OPTION){

                if(jugadores.get(jl_jugadores.getSelectedIndex()).isDisponible()){
                    if(equipos.get(jl_equipos.getSelectedIndex()).getPresupuesto()>jugadores.get(jl_jugadores.getSelectedIndex()).getPrecio()){
                        DefaultListModel modelo=(DefaultListModel) jl_jugadores.getModel();
                        equipos.get(jl_equipos.getSelectedIndex()).jugadores.add(jugadores.get(jl_jugadores.getSelectedIndex()));
                        equipos.get(jl_equipos.getSelectedIndex()).setPresupuesto(equipos.get(jl_equipos.getSelectedIndex()).getPresupuesto()-jugadores.get(jl_jugadores.getSelectedIndex()).getPrecio());
                        jugadores.get(jl_jugadores.getSelectedIndex()).setDisponible(false);
                        modelo.removeAllElements();
                        for (int i = 0; i <jugadores.size() ; i++) {
                            modelo.addElement(jugadores.get(i));
                        }
                        JOptionPane.showMessageDialog(this, "El jugador ha sido Comprado correctamente");
                        jl_jugadores.setModel(modelo);
                    }else{
                        JOptionPane.showMessageDialog(this, "Losentimos pero no tiene el equipo no tiene el presupuesto suficiente para este jugador!");
                    }

                }else{
                    JOptionPane.showMessageDialog(this, "Losentimos pero el jugador no esta disponible!");
                }

            }
        }
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        if (jl_jugadores.getSelectedIndex()>=0) {

            int response=JOptionPane.showConfirmDialog(this, "Seguro que desea modificar?","Confirmar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

            if(response==JOptionPane.OK_OPTION){

                try {
                    String nombre;
                    double precio;
                    String posicion;
                    double habilidad;
                    double tecnica;
                    double resistencia;
                    DefaultListModel modelo=(DefaultListModel) jl_jugadores.getModel();

                    nombre=JOptionPane.showInputDialog("Nombre nuevo");
                    precio=Double.parseDouble(JOptionPane.showInputDialog("Nuevo precio"));
                    posicion=JOptionPane.showInputDialog("Posicion nueva");
                    habilidad=Double.parseDouble(JOptionPane.showInputDialog("Nueva habilidad"));
                    tecnica=Double.parseDouble(JOptionPane.showInputDialog("Nueva tecnica"));
                    resistencia=Double.parseDouble(JOptionPane.showInputDialog("Nueva resistencia"));

                    jugadores.get(jl_jugadores.getSelectedIndex()).setNombre(nombre);
                    jugadores.get(jl_jugadores.getSelectedIndex()).setPrecio(precio);
                    jugadores.get(jl_jugadores.getSelectedIndex()).setPosicion(posicion);
                    jugadores.get(jl_jugadores.getSelectedIndex()).setHabilidad(habilidad);
                    jugadores.get(jl_jugadores.getSelectedIndex()).setTecnica(tecnica);
                    jugadores.get(jl_jugadores.getSelectedIndex()).setResistencia(resistencia);

                    modelo.removeAllElements();
                    for (int i = 0; i <jugadores.size() ; i++) {
                        modelo.addElement(jugadores.get(i));
                    }
                    JOptionPane.showMessageDialog(this, "El jugador ha sido modificado correctamente");
                    jl_jugadores.setModel(modelo);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Ocurrio un error vuelva a intentar");
                }
            }

        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        if (jl_jugadores.getSelectedIndex()>=0) {
            int response=JOptionPane.showConfirmDialog(this, "Seguro de eliminar?","Confirmar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

            if(response==JOptionPane.OK_OPTION){

                DefaultListModel modelo=(DefaultListModel) jl_jugadores.getModel();

                jugadores.remove(jl_jugadores.getSelectedIndex());
                modelo.removeAllElements();
                for (int i = 0; i <jugadores.size() ; i++) {
                    modelo.addElement(jugadores.get(i));
                }
                JOptionPane.showMessageDialog(this, "El Jugador ha sido eliminado correctamente");
                jl_jugadores.setModel(modelo);
            }
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        if (jl_equipos.getSelectedIndex()>=0) {

            int response=JOptionPane.showConfirmDialog(this, "Seguro que desea modificar?","Confirmar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

            if(response==JOptionPane.OK_OPTION){

                try {
                    String nombre;
                    double presupuesto;
                    int copas;
                    String estadio;
                    DefaultListModel modelo=(DefaultListModel) jl_equipos.getModel();

                    nombre=JOptionPane.showInputDialog("Nombre nuevo");
                    presupuesto=Double.parseDouble(JOptionPane.showInputDialog("Nuevo presupuesto"));
                    copas=Integer.parseInt(JOptionPane.showInputDialog("Nueva cantidad de copas"));
                    estadio=JOptionPane.showInputDialog("Nuevo Estadio");

                    equipos.get(jl_equipos.getSelectedIndex()).setNombre(nombre);
                    equipos.get(jl_equipos.getSelectedIndex()).setPresupuesto(presupuesto);
                    equipos.get(jl_equipos.getSelectedIndex()).setCopas(copas);
                    equipos.get(jl_equipos.getSelectedIndex()).setEstadio(estadio);

                    modelo.removeAllElements();
                    for (int i = 0; i <equipos.size() ; i++) {
                        modelo.addElement(equipos.get(i));
                    }
                    JOptionPane.showMessageDialog(this, "El equipo ha sido modificado correctamente");
                    jl_equipos.setModel(modelo);

                } catch (Exception e) {
                    JOptionPane.showMessageDialog(this, "Ocurrio un error vuelva a intentar");
                }
            }

        }
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        if (jl_equipos.getSelectedIndex()>=0) {
            int response=JOptionPane.showConfirmDialog(this, "Seguro de eliminar?","Confirmar",JOptionPane.YES_NO_OPTION,JOptionPane.QUESTION_MESSAGE);

            if(response==JOptionPane.OK_OPTION){

                DefaultListModel modelo=(DefaultListModel) jl_equipos.getModel();

                equipos.remove(jl_equipos.getSelectedIndex());
                modelo.removeAllElements();
                for (int i = 0; i <equipos.size() ; i++) {
                    modelo.addElement(equipos.get(i));
                }
                JOptionPane.showMessageDialog(this, "El equipo ha sido eliminado correctamente");
                jl_equipos.setModel(modelo);
            }
        }

    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        //Listar equipos
        DefaultListModel modelo=(DefaultListModel) jl_equipos.getModel();
        modelo.removeAllElements();
        for (int i = 0; i <equipos.size(); i++) {
            modelo.addElement(equipos.get(i));
        }

        jl_equipos.setModel(modelo);

        //Listar Jugadores
        DefaultListModel modelo2=(DefaultListModel) jl_jugadores.getModel();
        modelo2.removeAllElements();
        for (int i = 0; i <jugadores.size(); i++) {
            modelo2.addElement(jugadores.get(i));
        }

        jl_jugadores.setModel(modelo2);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        try {
            jugadores.add(new Jugador(tf_nombrejugador.getText(), Double.parseDouble(tf_precio.getText()), tf_posicion.getText(),true,  (Integer)js_habilidad.getValue(), (Integer)js_tecnica.getValue(), (Integer)js_resistencia.getValue()));
            JOptionPane.showMessageDialog(this, "Jugador creado con exito!");
            System.out.println(jugadores);

            tf_nombrejugador.setText("");
            tf_precio.setText("");
            tf_posicion.setText("");
            js_habilidad.setValue(0);
            js_tecnica.setValue(0);
            js_resistencia.setValue(0);

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error Vuelva a intentar");
        }
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        try {
            equipos.add(new Equipo(tf_nombreequipo.getText(), Double.parseDouble(tf_presupuesto.getText()), (Integer)js_copas.getValue(), tf_estadio.getText()));
            JOptionPane.showMessageDialog(this, "Equipo creado con exito!");

            tf_nombreequipo.setText("");
            tf_presupuesto.setText("");
            js_copas.setValue(0);
            tf_estadio.setText("");

        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Ocurrio un error Vuelva a intentar");
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton10ActionPerformed

        DefaultTreeModel modeloARBOL=(DefaultTreeModel)jt_liga.getModel();
            DefaultMutableTreeNode raiz=(DefaultMutableTreeNode)modeloARBOL.getRoot();
            raiz.removeAllChildren();
//obtener la persona a guardar
            DefaultListModel modeloLISTA=(DefaultListModel)jl_equipos.getModel();
            
            //ver si tiene equipo
            for (int j = 0; j < equipos.size(); j++) {
                for (int k = 0; k < equipos.get(j).jugadores.size(); k++) {
                    int centinela=-1;
                    for (int i = 0; i < raiz.getChildCount(); i++) {
                        if (raiz.getChildAt(i).toString().equals(equipos.get(j).getNombre())) {
                            //si ya existe le agrega al jugador
                            DefaultMutableTreeNode p=new DefaultMutableTreeNode(equipos.get(j).jugadores.get(k));
                            ((DefaultMutableTreeNode)raiz.getChildAt(i)).add(p);
                            centinela=1;
                        }  
                    }
                    if(centinela==-1){
                            DefaultMutableTreeNode n=new DefaultMutableTreeNode(equipos.get(j).getNombre());
                            DefaultMutableTreeNode p=new DefaultMutableTreeNode(equipos.get(j).jugadores.get(k));
                            n.add(p);
                            raiz.add(n);

                        }
                    
                }
            
        }
            
            
            modeloARBOL.reload();
    }//GEN-LAST:event_jButton10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new principal().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton10;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JList<String> jl_equipos;
    private javax.swing.JList<String> jl_jugadores;
    private javax.swing.JSpinner js_copas;
    private javax.swing.JSpinner js_habilidad;
    private javax.swing.JSpinner js_resistencia;
    private javax.swing.JSpinner js_tecnica;
    private javax.swing.JTree jt_liga;
    private javax.swing.JTextField tf_estadio;
    private javax.swing.JTextField tf_nombreequipo;
    private javax.swing.JTextField tf_nombrejugador;
    private javax.swing.JTextField tf_posicion;
    private javax.swing.JTextField tf_precio;
    private javax.swing.JTextField tf_presupuesto;
    // End of variables declaration//GEN-END:variables
ArrayList<Jugador>jugadores=new ArrayList();
ArrayList<Equipo>equipos=new ArrayList();
ArrayList<Equipo>Liga=new ArrayList();
ArrayList<Jugador>comprado=new ArrayList();
}
